# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        # Exclude .md and .markdown files to allow trailing whitespace (used for line breaks in Markdown)
        exclude: \.(md|markdown)$
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: check-toml
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=no]
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      # - id: terraform_docs
      #   args:
      #     - --hook-config=--path-to-file=README.md # Target file
      #     - --hook-config=--add-to-existing-file=true # Update existing README
      - id: terraform_fmt
      - id: terraform_tflint
      # - id: terraform_trivy
      - id: terraform_validate
